#!/usr/bin/env python3
"""Create a publication-style depth-resolved mcrA bubble plot.

The figure uses the ecology-ready lineage relative-abundance table generated by
13_prepare_ecology_tables.py. It is intended for depth-resolved EA samples.

Visual encoding
---------------
* facet rows: site
* facet columns: sampling month
* x position: lineage
* y position: measured sediment depth (cm; increasing downward)
* bubble area: lineage relative abundance (%)

The default lineage set is generated reproducibly: the nine most abundant
lineages across retained samples, plus the unresolved environmental lineage and
ANME-2d if either is not already represented. Values below --min-percent remain
in the exported figure-data table but are not drawn.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.lines import Line2D

MONTH_ORDER = ["September", "January", "April", "July"]
SITE_ORDER = ["EA1", "EA2", "EA3", "EA4"]
ANME2D = "ANME-2d / Methanoperedenaceae-related"
UNRESOLVED = "Unresolved environmental mcrA lineage"


def choose_lineages(lineage_counts: pd.DataFrame, top_n: int) -> list[str]:
    totals = lineage_counts.sum(axis=1).sort_values(ascending=False)
    selected = totals.head(top_n).index.tolist()
    for lineage in [ANME2D, UNRESOLVED]:
        if lineage in totals.index and lineage not in selected:
            selected.append(lineage)
    return selected


def short_label(lineage: str) -> str:
    replacements = {
        ANME2D: "ANME-2d",
        UNRESOLVED: "Unresolved env.",
        "Methanocellaceae-related": "Methanocellaceae-rel.",
        "Methanospirillaceae-related": "Methanospirillaceae-rel.",
        "Methanomicrobiales-related": "Methanomicrobiales-rel.",
    }
    return replacements.get(lineage, lineage)


def bubble_area(percent: np.ndarray | float) -> np.ndarray | float:
    """Marker area in points^2; area is approximately linear with abundance."""
    return 7.0 + np.asarray(percent) * 6.7


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--prepared-dir", required=True)
    ap.add_argument("--output-dir", required=True)
    ap.add_argument("--top-n", type=int, default=9,
                    help="Number of globally dominant lineages selected before forced inclusions")
    ap.add_argument("--min-percent", type=float, default=0.25,
                    help="Values below this relative abundance are retained in data but not drawn")
    ap.add_argument("--max-depth", type=float, default=40.0)
    ap.add_argument("--dpi", type=int, default=600)
    args = ap.parse_args()

    prep = Path(args.prepared_dir)
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    long = pd.read_csv(prep / "lineage_relative_abundance_long.tsv", sep="\t")
    counts = pd.read_csv(prep / "lineage_counts.tsv", sep="\t", index_col=0)

    long = long[
        long["depth_cm"].notna()
        & long["site"].isin(SITE_ORDER)
        & long["Month"].isin(MONTH_ORDER)
    ].copy()

    lineages = choose_lineages(counts, args.top_n)
    plot_df = long[long["lineage"].isin(lineages)].copy()
    plot_df["lineage_order"] = plot_df["lineage"].map({x: i for i, x in enumerate(lineages)})
    plot_df["site_order"] = plot_df["site"].map({x: i for i, x in enumerate(SITE_ORDER)})
    plot_df["month_order"] = plot_df["Month"].map({x: i for i, x in enumerate(MONTH_ORDER)})
    plot_df["plotted"] = plot_df["relative_abundance_pct"] >= args.min_percent
    plot_df = plot_df.sort_values(["site_order", "month_order", "depth_cm", "lineage_order"])

    plot_df[[
        "sample_id", "site", "Month", "depth_cm", "lineage",
        "relative_abundance_pct", "library_reads", "plotted",
    ]].to_csv(out / "mcrA_depth_bubble_data.tsv", sep="\t", index=False)

    nlin = len(lineages)
    panel_w = max(10.0, 1.2 * nlin)
    panel_h = args.max_depth + 2.0
    x_gap = 1.55
    y_gap = 5.2
    x_internal = np.linspace(0.65, panel_w - 0.95, nlin)

    fig, ax = plt.subplots(figsize=(18.6, 13.8))

    for r, site in enumerate(SITE_ORDER):
        y_base = (len(SITE_ORDER) - 1 - r) * (panel_h + y_gap)
        for c, month in enumerate(MONTH_ORDER):
            x_base = c * (panel_w + x_gap)
            ax.add_patch(Rectangle(
                (x_base, y_base), panel_w, args.max_depth,
                fill=False, linewidth=0.75, alpha=0.85, zorder=0,
            ))
            for depth in np.arange(10, args.max_depth, 10):
                yy = y_base + (args.max_depth - depth)
                ax.plot([x_base, x_base + panel_w], [yy, yy],
                        linewidth=0.35, alpha=0.22, zorder=0)

            present = not long[(long["site"] == site) & (long["Month"] == month)].empty
            if not present:
                ax.text(x_base + panel_w / 2, y_base + args.max_depth / 2,
                        "not sampled", ha="center", va="center",
                        fontsize=8.8, fontstyle="italic", alpha=0.5)

            if r == 0:
                ax.text(x_base + panel_w / 2, y_base + args.max_depth + 1.7,
                        month, ha="center", va="bottom",
                        fontsize=11.5, fontweight="bold")

            if r == len(SITE_ORDER) - 1:
                for j, lineage in enumerate(lineages):
                    ax.text(x_base + x_internal[j], y_base - 1.55,
                            short_label(lineage), ha="right", va="top",
                            rotation=57, fontsize=8.0)

            if c == 0:
                for depth in np.arange(0, args.max_depth + 0.1, 10):
                    yy = y_base + (args.max_depth - depth)
                    ax.text(x_base - 0.4, yy, f"{depth:g}",
                            ha="right", va="center", fontsize=8.5)

        ax.text(-1.25, y_base + args.max_depth / 2, site,
                ha="center", va="center", fontsize=11.5,
                fontweight="bold", rotation=90)

    scatter_handles = []
    for lineage in lineages:
        sub = plot_df[(plot_df["lineage"] == lineage) & plot_df["plotted"]]
        if sub.empty:
            continue
        xs, ys, sizes = [], [], []
        for _, row in sub.iterrows():
            r = SITE_ORDER.index(row["site"])
            c = MONTH_ORDER.index(row["Month"])
            y_base = (len(SITE_ORDER) - 1 - r) * (panel_h + y_gap)
            x_base = c * (panel_w + x_gap)
            xs.append(x_base + x_internal[int(row["lineage_order"])])
            ys.append(y_base + (args.max_depth - row["depth_cm"]))
            sizes.append(float(bubble_area(row["relative_abundance_pct"])))

        art = ax.scatter(xs, ys, s=sizes, alpha=0.80,
                         linewidths=0.45, edgecolors="white",
                         label=short_label(lineage), zorder=3)
        scatter_handles.append(art)

    lineage_legend = ax.legend(
        handles=scatter_handles,
        labels=[h.get_label() for h in scatter_handles],
        title="Lineage", loc="upper left", bbox_to_anchor=(1.003, 0.995),
        frameon=False, fontsize=8.3, title_fontsize=9.3,
        handletextpad=0.55, labelspacing=0.62, scatterpoints=1, markerscale=0.75,
    )
    ax.add_artist(lineage_legend)

    size_values = [1, 10, 25, 50, 90]
    size_handles = [
        Line2D([0], [0], marker="o", linestyle="None",
               markersize=np.sqrt(float(bubble_area(p))), label=f"{p}%")
        for p in size_values
    ]
    ax.legend(handles=size_handles, title="Relative abundance",
              loc="upper left", bbox_to_anchor=(1.003, 0.45),
              frameon=False, fontsize=8.3, title_fontsize=9.3,
              labelspacing=1.0)

    total_w = len(MONTH_ORDER) * panel_w + (len(MONTH_ORDER) - 1) * x_gap
    total_h = len(SITE_ORDER) * panel_h + (len(SITE_ORDER) - 1) * y_gap
    ax.text(-2.35, total_h / 2, "Sediment depth (cm)",
            ha="center", va="center", rotation=90, fontsize=11.2)
    ax.set_xlim(-2.9, total_w + 6.1)
    ax.set_ylim(-8.2, total_h + 3.7)
    ax.axis("off")

    fig.tight_layout()
    fig.savefig(out / "mcrA_depth_bubble.png", dpi=args.dpi, bbox_inches="tight")
    fig.savefig(out / "mcrA_depth_bubble.pdf", bbox_inches="tight")
    fig.savefig(out / "mcrA_depth_bubble.svg", bbox_inches="tight")
    plt.close(fig)

    pd.DataFrame({"displayed_lineage": lineages}).to_csv(
        out / "mcrA_depth_bubble_lineages.tsv", sep="\t", index=False
    )

    print(f"Depth-resolved samples: {plot_df['sample_id'].nunique()}")
    print(f"Displayed lineages: {len(lineages)}")
    print(f"Minimum drawn relative abundance: {args.min_percent}%")
    print("Wrote figure, vector versions, lineage list, and exact figure data to", out)


if __name__ == "__main__":
    main()
